apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
spec:
  replicas: 3  # Number of replicas/instances of your application
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: youracr.azurecr.io/dotnet-app:latest  # Path to your container image in ACR
        ports:
        - containerPort: 80  # Port your application listens on

